### ISSUE TITLE
Undocumented: Content Form SDK Method - openLinkDialog

### ISSUE THREAD

**Issue by JohnRSim** [oracle/content-and-experience-toolkit#11]
Is the following method supported or is it experimental "openLinkDialog" as it is undocumented.

https://docs.oracle.com/en/cloud/paas/content-cloud/solutions/custom-content-form-field-object.html
The method works on OCE but not in the OCE Toolkit 21.1.3 in developer mode.

```
item.getFieldByName(LargeTextField).openLinkDialog().then((data) => {
	console.log('openLinkDialog body',data);
	
}).catch(function(error){
	// handle error
	console.error('Error:', error);
});
```

**Comment by VijRajan** [comment]
"openLinkDialog" method is not supported and it is for internal use.
