### ISSUE TITLE
self signed certificate in certificate chain

### ISSUE THREAD

**Issue by Brindha16** [oracle/content-and-experience-toolkit#14]
Hi,

Trying to connect to a server using CLI and the Confidential application (to skip Chrome).

this is the command I am using to register the server :

cec register-server NAME --endpoint https://ocepm-oce1234.cec.ocp.oraclecloud.com -u username -p 'password' --idcsurl https://idcs-1234123412341234123412341234.identity.oraclecloud.com --clientid idididididididididididididid --clientsecret secret-secret-secret-secret-secret --scope https://SCOPESCOPESCOPESCOPE.cec.ocp.oraclecloud.com:443/urn:opc:cec:all

Getting the below error message; tried using the latest version of the toolkit till 21.6.1 release-

C:\Users\\GitSource\cec-src>cec list --server PROD
Tue, 16 Nov 2021 16:47:36 GMT
OCM Toolkit 21.6.1
ERROR: Failed to get OAuth token
FetchError: request to https://idcs-1234123412341234123412341234.identity.oraclecloud.com/oauth2/v1/token failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (C:\content-and-experience-toolkit-21.6.1\sites\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'SELF_SIGNED_CERT_IN_CHAIN',
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
 - failed to connect to the server
Not sure how to fix this. Can someone help?

**Comment by hzeng99** [comment]
What's your node version? 
Also 21.6.1 is old, please update to the latest

**Comment by Brindha16** [comment]
v12.18.0

**Comment by Brindha16** [comment]
I was getting the same error when using the latest content toolkit version as well.

**Comment by hzeng99** [comment]
can you try to register the server with just user/password and see if commands work?

**Comment by Brindha16** [comment]
I tried but I need to skip the Chrome pop up step as I am not getting the login screen (as it is integrated with our Azure AD). So, used this help documentation to skip the headless Chrome step : https://github.com/oracle/content-and-experience-toolkit/blob/master/sites/doc/IDCS-App.md 

As I am not getting the login screen, it just times out and getting "Failed to connect to server"...

Thanks!

**Comment by hzeng99** [comment]
You can do:
- register the server with user/passwd
- on browser, go to OCM server /documents/web?IdcService=GET_OAUTH_TOKEN
- copy the tokenValue
- run 
   cec sot "tokenValue" -s <register server>
- cec l -s <register server>

**Comment by hzeng99** [comment]
As for the issue "self signed certificate in certificate chain", seems to do with your SSL set up.
I will see if I can find more info

**Comment by Brindha16** [comment]
Thank you so much!!!

**Comment by Brindha16** [comment]
Hi, just checking if there is any update on this issue.. Thanks!

**Comment by Brindha16** [comment]
Updated the toolkit version to latest.. still getting the same error message.

**Comment by hzeng99** [comment]
The issue "self signed certificate in certificate chain" should not caused by Toolkit.
More to do with your SSL setup on your local machine

**Comment by Brindha16** [comment]
thank you! We found that it was a networking issue.. Now I am able to make the connection successfully. Closing this thread. Thank you for your time and help again!
