### ISSUE TITLE
Not able to install on windows

### ISSUE THREAD

**Issue by vivekg8** [oracle/content-and-experience-toolkit#15]
getting the following error after following the oracle recommended steps to install the toolkit

C:\CloudDocs\content-and-experience-toolkit\content-and-experience-toolkit-master\sites>cec develop
'cec' is not recognized as an internal or external command,
operable program or batch file.

**Comment by hzeng99** [comment]
Did you do this:

Run SystemPropertiesAdvanced.exe, edit Environment Variables and add <your download path>\content-and-experience-toolkit\sites\node_modules\.bin to the PATH variable, replacing <your download path> as appropriate.

After set the PATH, open a new terminal in Admin mode, type "cec"

**Comment by vivekg8** [comment]
> Did you do this:
> 
> Run SystemPropertiesAdvanced.exe, edit Environment Variables and add \content-and-experience-toolkit\sites\node_modules.bin to the PATH variable, replacing as appropriate.
> 
> After set the PATH, open a new terminal in Admin mode, type "cec"

Hey, Thanks for the help. I was able to install and run the "cec" command as well.

Just one question, can we move Digital assets from one OCM environment to another OCE environment(example Dev to Prod) using OCM toolkit?

**Comment by hzeng99** [comment]
You can use command 
  cec transfer-content

**Comment by vivekg8** [comment]
Thank you.
