### ISSUE TITLE
Error while running install-cec

### ISSUE THREAD

**Issue by vinay-kum** [oracle/content-and-experience-toolkit#2]
Getting below exception while running 
**VINAYKUM-mac:**cec-components vinaykum$ sudo npm run install-cec

> cec-components@19.2.2-b install-cec /driveE/oce/sites/cec-components
> npm install -g bin/cec

npm ERR! path /driveE/oce/sites/cec-components/bin/cec/node_modules/wrap-ansi/node_modules/ansi-regex
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access '/driveE/oce/sites/cec-components/bin/cec/node_modules/wrap-ansi/node_modules/ansi-regex'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

This was working fine probably a month back, but from above error message it seems that install-cec is building the node_module directory on as expected because it exist under /cec-components.

**Comment by steveaburns** [comment]
Please clean out node_modules:

cd cec-components
rm -rf node_modules
rm -rf bin/cec/node_modules
make sure cec CLI is uninstalled
sudo npm uninstall -g bin/cec

then try again:
cd cec-components
npm install
sudo run npm install-cec

As an alternative - don't do the sudo-part, install bin/cec direct...  then put <path>/cec-components/node_modules/.bin on your path, or perhaps better, sudo ln -s <path>/cec-components/node_modules/.bin/cec /usr/local/bin/cec
cd cec-components
npm install
npm install bin/cec

**Comment by vinay-kum** [comment]
Thanks Steve, followed your instruction and it work like a charm
