### ISSUE TITLE
Failed to open the login page ERROR: failed to connect to the server

### ISSUE THREAD

**Issue by brindha-mec** [oracle/content-and-experience-toolkit#24]
Hello,

Trying to run the cec commands to transfer the site from our DEV instance to PROD instance. Tried using cec-register command with OAuth token and also with username/password. When I give cec list --server DEV, it is trying to open the Chrome browser and as our environments are synced with our Azure AD (Federated), it is skipping the login part and getting this error message :

C:\GitSource\cec-src>cec list --server DEV
Wed, 23 Nov 2022 21:45:01 GMT
Content Toolkit 21.11.2
Failed to open the login page
ERROR: failed to connect to the server

It was working till yesterday..  To avoid the Chrome browser step, creating a confidential application as mentioned here - https://github.com/oracle/content-and-experience-toolkit/blob/master/sites/doc/IDCS-App.md - is this the only option?

Thanks!

**Comment by tcaruth** [comment]
you can get an oAuth token from this URL
`https://YOUR-INSTANCE-URL.cec.ocp.oraclecloud.com/documents/web?IdcService=GET_OAUTH_TOKEN`

and set it to your server with
`cec set-oauth-token`
https://docs.oracle.com/en/cloud/paas/content-cloud/content-toolkit-cli/index.html#cec-set-oauth-token

**Comment by hzeng99** [comment]
The steps Travis gave above is the correct approach

**Comment by brindha-mec** [comment]
I usually connect to our DEV and PROD instances using this oAuth token method and I had no issues until today.
I use this command to set the oauth token : 

cec set-oauth-token "<<<OAUTH TOKEN FORM THE GET_OAUTH_TOKEN URL>>> -s DEV and -s PROD for PROD URL.
The connectivity to PROD instance works fine  ( cec list --server PROD ) and returning all the sites, templates, components in the PROD site. But, when I run cec list --server DEV, it is trying to open a Chrome browser and it is not prompting to enter the login credentials (as the instance is synced with my Azure AD); getting the below error in the command line -

Failed to open the login page
ERROR: failed to connect to the server

**Comment by brindha-mec** [comment]
Just as a side note, when I run cec list --server PROD, it is not opening the Chrome browser and just connects just fine.. Maybe my question is what should be done to skip this whole Chrome browser step when running the cec list command?

Thanks!

**Comment by tcaruth** [comment]
> C:\GitSource\cec-src>cec list --server DEV
> Wed, 23 Nov 2022 21:45:01 GMT
> Content Toolkit 21.11.2
> Failed to open the login page
> ERROR: failed to connect to the server

Try updating your toolkit version. Also, what version are the OCM instances on?

**Comment by brindha-mec** [comment]
Thanks; I will try updating my toolkit version. But, not sure how PRD works fine but getting this issue only in DEV? Thought User/Access related things might have changed in DEV instance - like Federated vs non-federated accounts.. 

DEV : Version: 22.11.1
Build: 2211091108

PRD : Version: 22.11.1
Build: 2211091108

**Comment by tcaruth** [comment]
Did updating the toolkit work? I update with each new version and haven't run into the issue you're having on your instance.

You could also try registering the servers again, but since you're setting the token I'm not sure it wouild make much difference.

@hzeng99 are there any other troubleshooting steps to take that you can think of?

**Comment by brindha-mec** [comment]
Yes, tried using the latest version; I am able to connect to PRD but getting the same error/Chrome popup in DEV.

checked this documentation - https://github.com/oracle/content-and-experience-toolkit/blob/master/sites/doc/IDCS-App.md (Using an IDCS Application to access CEC Instance to have a CLI without Chromium popup for Authentication) - this doc seems to be so relevant to my issue. I have requested our admins to create a confidential app and will try to make a connection... But, it would be really helpful to know what is causing this issue. 

Thanks!

**Comment by hzeng99** [comment]
After run 
  cec set-oauth-token <token>
if chrome still popups, it means it fails to authenticate with the token, it could caused by
(1) the token is not valid
(2) the token and the server not match

**Comment by brindha-mec** [comment]
@hzeng99  Thank you for your response.
Got the token from the URL - https://DEVOCMinstance.cec.ocp.oraclecloud.com/documents/web?IdcService=GET_OAUTH_TOKEN and tried as soon as I got the token.

Our admins created the confidential app and I was able to register the server -

cec register-server NAME --endpoint https://ocepm-oce1234.cec.ocp.oraclecloud.com -u username -p 'password' --idcsurl https://idcs-1234123412341234123412341234.identity.oraclecloud.com --clientid idididididididididididididid --clientsecret secret-secret-secret-secret-secret --scope https://SCOPESCOPESCOPESCOPE.cec.ocp.oraclecloud.com:443/urn:opc:cec:all

and also used cec set-oauth-token "OAUTH TOKEN" -s DEV to set the OAuth token - When I try the cec list command, getting this error now -

ERROR: Failed to get OAuth token - A federated user can't perform local authentication.
ERROR: failed to connect to the server

Could you please advise?

Thanks!

**Comment by brindha-mec** [comment]
**Now, not getting the Chromium popup.

**Comment by hzeng99** [comment]
if you register a server with IDCS app, you should not run set-oauth-token. 
So now the PRD server works but for DEV neither IDCS app nor set-oauth-token works?

**Comment by brindha-mec** [comment]
yes, correct. I had no issues with PRD server before. I use OAuth token method to access PROD and it works fine.
DEV is not working neither in IDCS app nor in set-oauth-token method.. Confirmed with our system admin that my user account set-up is same in DEV and PROD (Federated).

**Comment by brindha-mec** [comment]
I just uninstalled content experience toolkit and installing it (the new version again) from scratch.. It is in progress.. I will post as soon as I try again.. Thank you.

**Comment by brindha-mec** [comment]
same error again -

Tue, 29 Nov 2022 04:11:33 GMT
Content Toolkit 22.11.1
cec list --server DEV
ERROR: Failed to get OAuth token A federated user can't perform local authentication. (Tue, 29 Nov 2022 04:11:39 GMT)
ERROR: failed to connect to the server (Tue, 29 Nov 2022 04:11:39 GMT)
Elapsed time: 6s

**Comment by brindha-mec** [comment]
Cleared my browser cache, tried a new instance of my command prompt and just tried running the cec set-oauth-token command and tried cec list , I am able to connect to DEV instance successfully!! 

Thank you so much @hzeng99 and @tcaruth !! 👍 

Thanks!
