### ISSUE TITLE
Cannot install in /sites, server not found

### ISSUE THREAD

**Issue by R1JeffSteel** [oracle/content-and-experience-toolkit#27]
Using node 19.4.0, npm 9.2.0, on macOS 12.6.2 (Intel)

npm install in /sites hangs at : 
reify:es5-ext: timing reifyNode:node_modules/es6-iterator/node_modules/es5-ext

Eventually, install times out and I get the following errors:
npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to https://artifacthub-phx.oci.oraclecorp.com/api/npm/npmjs-remote/yocto-queue/-/yocto-queue-0.1.0.tgz failed, reason: getaddrinfo ENOTFOUND artifacthub-phx.oci.oraclecorp.com
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

Note that:
1. I'm not behind any proxies when attempting to install
2. Attempting to ping "artifacthub-phx.oci.oraclecorp.com" comes back as "not found", so it appears that this server is down or otherwise unavailable

**Comment by hzeng99** [comment]
Please delete file package-lock.json and run npm install again

**Comment by R1JeffSteel** [comment]
That did the trick. Thank you!
