### ISSUE TITLE
Error Indexing Site

### ISSUE THREAD

**Issue by tcaruth** [oracle/content-and-experience-toolkit#30]
We had been using a cloud compute to run a script that downloaded toolkit version 22.10.1, registered a server, and performed the `cec index-site` command but while updating the script discovered this error. I did some troubleshooting of my own and deleted all my page index assets. The command below ran successfully and created the required assets. When running it again, I get the output below. This suggests there's some broken logic in the update asset methods, but I was unable to find exactly where.

I also tried running on a totally unrelated different site with a different asset type and received the same error.

Can somebody help me diagnose what's going on? Do any other toolkit users use this command and have issues with it?

```sh
❯ cec index-site [redacted] -s [redacted] -c [redacted] -p
Tue, 14 Feb 2023 19:42:06 GMT
Content Toolkit 23.2.1
cec index-site "[redacted]" --server [redacted] --contenttype "[redacted]" --publish true
 - get CSRF token
 - get /sites/management/api/v1/sites/name:[redacted]
 - find folder pages (Id: F51009A7C82861B4A76469F8044532EB719E649C0EEC)
 - site: [redacted], default language: en-US, channel token: 294436b7dd6c4570988cae88f0ee7c90
 - query channel
 - site localization policy: Default
 - query site repository
 - query content type [redacted]
 - query site structure
 - total number of files: 141
 - downloading files [132, 140] ...
 - content types used in the site: [redacted]
 - total number of files: 141
 - downloading files [132, 140] ...
 - query page data (en-US)
 - query content on the pages
 - page logs is set hidden from search
 - total items: 146
 - will create 0 page index items
 - will update 146 page index items
ERROR:  (Tue, 14 Feb 2023 19:42:34 GMT)
TypeError: Cannot read properties of undefined (reading 'pagename') (Tue, 14 Feb 2023 19:42:34 GMT)
[13:42:34] The following tasks did not complete: index-site
[13:42:34] Did you forget to signal async completion?
Elapsed time: 28s
```

**Comment by hzeng99** [comment]
it's a bug, the fix will be in 23.2.2.
In the meantime, you can delete the existing items and run index-site to create new.

**Comment by tcaruth** [comment]
Thanks Hui

Is there a list of identified breaks for the toolkit available someplace? I spent quite some time troubleshooting how the command works, which could've been avoided if I knew it was going to be addressed in the coming weeks.

**Comment by hzeng99** [comment]
We don't have such list for now. May consider building one. Thanks
